"""Init database

Revision ID: f2dbd76df564
Revises: 364e58a56950
Create Date: 2026-07-16 22:38:44.353732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dbd76df564'
down_revision: Union[str, None] = '364e58a56950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("chats", sa.Column("public_id", sa.UUID(), nullable=True))

    # Шаг 2: Генерируем уникальный UUID для каждой существующей строки
    # (Используем сырой SQL, так как это самый надежный способ в миграциях)
    op.execute("UPDATE chats SET public_id = gen_random_uuid()")

    # Шаг 3: Теперь, когда пустых строк нет, делаем колонку NOT NULL
    op.alter_column("chats", "public_id", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'public_id')
    # ### end Alembic commands ###
